T/zip 64 download tokens
harvard-dce/zoom-recording-ingester pull request #131
Opened 2021-06-22 18:58 UTC by nataliemona

2021-06-22 21:22 UTC, nataliemona commented on functions/zoom-uploader.py
> +            if e.response.status_code == 404:
Status code is an integer... not a string... whoops

2021-06-28 17:41 UTC, lbjay commented on functions/slack/handler.py
> +    r.raise_for_status()
there ought to be a pylint warning for this exact bug

2021-07-01 18:59 UTC, lbjay requested changes
Just one small change

2021-07-01 18:59 UTC, lbjay commented on tests/conftest.py
> +        on_demand_ingest = True if zoom_event == "on.demand.ingest" else False
Hmmm. Why not 
```
on_demand_ingest = zoom_event == "on.demand.ingest"
```
?

2021-07-01 20:31 UTC, merged